server:
  port: 8080

spring:
  application:
    name: profile_back

  datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: root@Mysql12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
